/**
 * Tests for NodeCryptoHashProvider.
 *
 * Per AD-012 v2 (Verification Strategy) + AD-006A v2 (Golden Reference Governance).
 *
 * Strategy:
 *   1. Load MANIFEST.json (the architectural truth — verified cross-language)
 *   2. For each positive fixture, verify both encodings match expected
 *   3. Verify the encoding asymmetry (RawDigestB64 ≠ HexDigestB64)
 *   4. Verify determinism (multiple calls = identical output)
 *   5. Verify length invariants (44 vs 88)
 *
 * Cross-language guarantee:
 *   The MANIFEST.json values were generated by 3 independent tools (OpenSSL,
 *   Node, Python). Our provider must match all three.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { NodeCryptoHashProvider } from '../NodeCryptoHashProvider';
import { HashError } from '../HashProvider';

const FIXTURES_DIR = join(__dirname, '..', 'fixtures');

interface PositiveFixture {
  name: string;
  input_file: string;
  input_size_bytes: number;
  sha256_hex: string;
  raw_digest_b64: string;
  hex_digest_b64: string;
  raw_digest_b64_length: number;
  hex_digest_b64_length: number;
}

interface Manifest {
  positive: PositiveFixture[];
  cross_language: Array<{
    sha256_hex_consensus: string;
    raw_digest_b64_consensus: string;
    tools_agreed: string[];
  }>;
}

describe('NodeCryptoHashProvider', () => {
  const provider = new NodeCryptoHashProvider();
  let manifest: Manifest;

  beforeAll(async () => {
    const content = await fs.readFile(join(FIXTURES_DIR, 'MANIFEST.json'), 'utf-8');
    manifest = JSON.parse(content);
  });

  describe('Contract', () => {
    it('declares SHA-256 algorithm', () => {
      expect(provider.algorithm).toBe('SHA-256');
    });

    it('declares implementation name', () => {
      expect(provider.implementationName).toContain('node:crypto');
      expect(provider.implementationName).toContain('SHA-256');
    });
  });

  describe('Length invariants (defensive)', () => {
    it('computeRawDigest always returns 44 characters for any input', () => {
      const inputs = ['', 'a', 'hello', 'أرض المبارك', Buffer.alloc(1000)];
      for (const input of inputs) {
        const result = provider.computeRawDigest(input);
        expect(result.length).toBe(44);
      }
    });

    it('computeHexDigest always returns 88 characters for any input', () => {
      const inputs = ['', 'a', 'hello', 'أرض المبارك', Buffer.alloc(1000)];
      for (const input of inputs) {
        const result = provider.computeHexDigest(input);
        expect(result.length).toBe(88);
      }
    });
  });

  describe('Encoding asymmetry (CRITICAL per AD-009 v2)', () => {
    it('RawDigestB64 and HexDigestB64 are DIFFERENT for the same input', () => {
      const inputs = [
        'Hello, World!',
        'أرض المبارك للسيارات',
        '<Invoice><ID>X</ID></Invoice>',
      ];
      for (const input of inputs) {
        const raw = provider.computeRawDigest(input);
        const hex = provider.computeHexDigest(input);
        expect(raw).not.toBe(hex);
        expect(raw.length).toBe(44);
        expect(hex.length).toBe(88);
      }
    });

    it('HexDigestB64 decoded gives the hex string of the SHA-256', () => {
      // This proves the encoding semantics exactly
      const input = 'Hello, World!';
      const hexDigest = provider.computeHexDigest(input);
      const decoded = Buffer.from(hexDigest, 'base64').toString('utf-8');
      // Decoded should be a 64-char lowercase hex string
      expect(decoded).toMatch(/^[0-9a-f]{64}$/);
      expect(decoded.length).toBe(64);
    });

    it('RawDigestB64 decoded gives the 32 raw SHA-256 bytes', () => {
      const input = 'Hello, World!';
      const rawDigest = provider.computeRawDigest(input);
      const decoded = Buffer.from(rawDigest, 'base64');
      expect(decoded.length).toBe(32); // SHA-256 = 32 bytes
    });
  });

  describe('Determinism', () => {
    it('produces identical output for identical input (RawDigest)', () => {
      const input = 'deterministic test';
      const r1 = provider.computeRawDigest(input);
      const r2 = provider.computeRawDigest(input);
      const r3 = provider.computeRawDigest(input);
      expect(r1).toBe(r2);
      expect(r2).toBe(r3);
    });

    it('produces identical output for identical input (HexDigest)', () => {
      const input = 'deterministic test';
      const r1 = provider.computeHexDigest(input);
      const r2 = provider.computeHexDigest(input);
      expect(r1).toBe(r2);
    });

    it('produces identical output across multiple provider instances', () => {
      const input = 'hello';
      const p1 = new NodeCryptoHashProvider();
      const p2 = new NodeCryptoHashProvider();
      expect(p1.computeRawDigest(input)).toBe(p2.computeRawDigest(input));
      expect(p1.computeHexDigest(input)).toBe(p2.computeHexDigest(input));
    });
  });

  describe('Input format normalization', () => {
    it('treats string and Buffer identically (UTF-8)', () => {
      const str = 'identical';
      const buf = Buffer.from(str, 'utf-8');
      expect(provider.computeRawDigest(str)).toBe(provider.computeRawDigest(buf));
      expect(provider.computeHexDigest(str)).toBe(provider.computeHexDigest(buf));
    });

    it('treats Uint8Array and Buffer identically', () => {
      const buf = Buffer.from('test', 'utf-8');
      const arr = new Uint8Array(buf);
      expect(provider.computeRawDigest(arr)).toBe(provider.computeRawDigest(buf));
    });

    it('handles empty input deterministically (well-known empty hash)', () => {
      // SHA-256("") = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      const expected_raw = '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';
      const raw = provider.computeRawDigest('');
      expect(raw).toBe(expected_raw);
    });
  });

  describe('Golden Fixtures (positive, from MANIFEST.json)', () => {
    it('manifest is loaded with positive fixtures', () => {
      expect(manifest.positive.length).toBeGreaterThanOrEqual(6);
    });

    // Dynamically generate one test per positive fixture
    it('all positive fixtures produce expected RawDigestB64', async () => {
      for (const fixture of manifest.positive) {
        const inputPath = join(FIXTURES_DIR, fixture.input_file);
        const input = await fs.readFile(inputPath); // Buffer, byte-accurate
        const actual = provider.computeRawDigest(input);

        if (actual !== fixture.raw_digest_b64) {
          throw new Error(
            `RawDigestB64 mismatch for "${fixture.name}":\n` +
            `  Expected (from MANIFEST, cross-verified): ${fixture.raw_digest_b64}\n` +
            `  Actual   (from NodeCryptoHashProvider):   ${actual}\n` +
            `  Input file: ${fixture.input_file} (${fixture.input_size_bytes} bytes)`
          );
        }
        expect(actual).toBe(fixture.raw_digest_b64);
      }
    });

    it('all positive fixtures produce expected HexDigestB64', async () => {
      for (const fixture of manifest.positive) {
        const inputPath = join(FIXTURES_DIR, fixture.input_file);
        const input = await fs.readFile(inputPath);
        const actual = provider.computeHexDigest(input);

        if (actual !== fixture.hex_digest_b64) {
          throw new Error(
            `HexDigestB64 mismatch for "${fixture.name}":\n` +
            `  Expected (from MANIFEST, cross-verified): ${fixture.hex_digest_b64}\n` +
            `  Actual   (from NodeCryptoHashProvider):   ${actual}\n` +
            `  Input file: ${fixture.input_file}`
          );
        }
        expect(actual).toBe(fixture.hex_digest_b64);
      }
    });
  });

  describe('Cross-language verification (proves Node matches OpenSSL + Python)', () => {
    it('Node crypto matches consensus of OpenSSL + Python for UBL invoice', async () => {
      expect(manifest.cross_language.length).toBeGreaterThan(0);
      const xv = manifest.cross_language[0];
      expect(xv.tools_agreed).toContain('OpenSSL 3.0.13');
      expect(xv.tools_agreed).toContain('Python 3.12.3 hashlib');

      // Read the input file
      const input = await fs.readFile(join(FIXTURES_DIR, 'cross-language', 'ubl-invoice-input.txt'));
      const actual = provider.computeRawDigest(input);
      expect(actual).toBe(xv.raw_digest_b64_consensus);
    });
  });

  describe('Known SHA-256 test vectors (universal reference)', () => {
    it('matches SHA-256("") = e3b0c442... (NIST reference)', () => {
      const raw = provider.computeRawDigest('');
      expect(raw).toBe('47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=');
    });

    it('matches SHA-256("abc") = ba7816bf... (NIST FIPS 180-4 Appendix A.1)', () => {
      const raw = provider.computeRawDigest('abc');
      // SHA-256("abc") = ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
      expect(raw).toBe('ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0=');
    });
  });

  describe('computeDigestBytes (canonical digest — ADR-026)', () => {
    it('returns exactly 32 bytes (SHA-256 output size)', () => {
      const inputs = ['', 'a', 'hello', 'أرض المبارك', Buffer.alloc(1000)];
      for (const input of inputs) {
        const digest = provider.computeDigestBytes(input);
        expect(Buffer.isBuffer(digest)).toBe(true);
        expect(digest.length).toBe(32);
      }
    });

    it('matches SHA-256("abc") NIST vector byte-for-byte (FIPS 180-4 A.1)', () => {
      const digest = provider.computeDigestBytes('abc');
      expect(digest.toString('hex')).toBe(
        'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
      );
    });

    it('matches SHA-256("") NIST vector byte-for-byte', () => {
      const digest = provider.computeDigestBytes('');
      expect(digest.toString('hex')).toBe(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
      );
    });

    it('is the canonical source: equals base64-decode of computeRawDigest', () => {
      // ADR-026 invariant: RawDigestB64 is a derived VIEW of these bytes.
      const inputs = ['Hello, World!', 'أرض المبارك للسيارات', Buffer.alloc(500, 7)];
      for (const input of inputs) {
        const bytes = provider.computeDigestBytes(input);
        const fromB64 = Buffer.from(provider.computeRawDigest(input), 'base64');
        expect(bytes.equals(fromB64)).toBe(true);
      }
    });

    it('is deterministic across calls and instances', () => {
      const input = 'deterministic digest';
      const p2 = new NodeCryptoHashProvider();
      expect(provider.computeDigestBytes(input).equals(p2.computeDigestBytes(input))).toBe(true);
    });

    it('treats string and Buffer identically (UTF-8)', () => {
      const str = 'identical';
      const buf = Buffer.from(str, 'utf-8');
      expect(provider.computeDigestBytes(str).equals(provider.computeDigestBytes(buf))).toBe(true);
    });
  });
});
