// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Environment resolution that works in BOTH the browser (Vite: import.meta.env)
 * and the Node Runtime (process.env).
 */
function readEnv(key: string): string | undefined {
  try {
    const metaEnv = (import.meta as unknown as { env?: Record<string, string> })
      .env;
    const v = metaEnv?.[key];
    if (v != null && v !== '') return v;
  } catch {
    // import.meta not available — fall through to process.env
  }
  if (
    typeof process !== 'undefined' &&
    process.env &&
    process.env[key] != null &&
    process.env[key] !== ''
  ) {
    return process.env[key];
  }
  return undefined;
}

/**
 * LAZY singleton. The Node Runtime injects its own client
 * (createSupabaseRuntimeClient) and never uses this one — but importing any
 * Domain module transitively loads this file. So the client must be built ON
 * FIRST USE, not at import time: in Node it is simply never touched, hence never
 * built, hence never throws for missing browser env.
 *
 * A Proxy preserves the existing `import { supabase }` usage in the frontend
 * unchanged while deferring construction.
 */
let _client: SupabaseClient<Database> | null = null;

function getClient(): SupabaseClient<Database> {
  if (_client) return _client;

  const url = readEnv('VITE_SUPABASE_URL') ?? readEnv('SUPABASE_URL');
  const key =
    readEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ??
    readEnv('SUPABASE_PUBLISHABLE_KEY') ??
    readEnv('SUPABASE_ANON_KEY');

  if (!url || !key) {
    throw new Error(
      'supabase singleton: missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. ' +
        'In the Node Runtime, inject a client via createSupabaseRuntimeClient instead ' +
        'of using this browser singleton.'
    );
  }

  const browserStorage =
    typeof localStorage !== 'undefined' ? localStorage : undefined;

  _client = createClient<Database>(url, key, {
    auth: {
      storage: browserStorage,
      persistSession: typeof localStorage !== 'undefined',
      autoRefreshToken: typeof localStorage !== 'undefined',
    },
  });
  return _client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    const client = getClient();
    const value = Reflect.get(client as unknown as object, prop, receiver);
    return typeof value === 'function' ? value.bind(client) : value;
  },
}) as SupabaseClient<Database>;
