// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Environment resolution that works in BOTH the browser (Vite: import.meta.env)
 * and the Node Runtime (process.env).
 */
function readEnv(key: string): string | undefined {
  try {
    const metaEnv = (import.meta as unknown as { env?: Record<string, string> })
      .env;
    const v = metaEnv?.[key];
    if (v != null && v !== '') return v;
  } catch {
    // import.meta not available — fall through to process.env
  }
  if (
    typeof process !== 'undefined' &&
    process.env &&
    process.env[key] != null &&
    process.env[key] !== ''
  ) {
    return process.env[key];
  }
  return undefined;
}

/**
 * LAZY singleton, with an optional Runtime override.
 *
 * Browser: built on first use from import.meta.env (unchanged behaviour).
 *
 * Node Runtime: the Runtime injects its own service-role client via
 * setRuntimeSupabaseClient() at startup. Domain modules that still import this
 * singleton directly (e.g. invoiceDataLoader — pending the Item 5 explicit-
 * injection refactor) then transparently use the Runtime's client. This is the
 * bridge that lets the Hosting Layer host Domain authorities today; the clean
 * end state remains explicit per-call injection.
 */
let _client: SupabaseClient<Database> | null = null;
let _runtimeOverride: SupabaseClient<Database> | null = null;

/** Runtime-only: install the client every default `supabase` usage resolves to. */
export function setRuntimeSupabaseClient(
  client: SupabaseClient<Database>
): void {
  _runtimeOverride = client;
}

function getClient(): SupabaseClient<Database> {
  if (_runtimeOverride) return _runtimeOverride;
  if (_client) return _client;

  const url = readEnv('VITE_SUPABASE_URL') ?? readEnv('SUPABASE_URL');
  const key =
    readEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ??
    readEnv('SUPABASE_PUBLISHABLE_KEY') ??
    readEnv('SUPABASE_ANON_KEY');

  if (!url || !key) {
    throw new Error(
      'supabase singleton: missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. ' +
        'In the Node Runtime, install a client via setRuntimeSupabaseClient() instead ' +
        'of using this browser singleton.'
    );
  }

  const browserStorage =
    typeof localStorage !== 'undefined' ? localStorage : undefined;

  _client = createClient<Database>(url, key, {
    auth: {
      storage: browserStorage,
      persistSession: typeof localStorage !== 'undefined',
      autoRefreshToken: typeof localStorage !== 'undefined',
    },
  });
  return _client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    const client = getClient();
    const value = Reflect.get(client as unknown as object, prop, receiver);
    return typeof value === 'function' ? value.bind(client) : value;
  },
}) as SupabaseClient<Database>;
