/**
 * CanonicalizationProvider — Abstraction over XML canonicalization implementations.
 *
 * Architectural references:
 * - AD-001 Pipeline Phase 2: Canonicalize XML
 * - AD-006 v2: Canonicalization Strategy
 * - AD-012 v2: Provider pattern for dependency injection
 *
 * Purpose:
 *   XML signing is a chain of trust. Any change to the canonicalization output —
 *   even a single byte — invalidates the signature. The implementation choice has
 *   profound implications, so we wrap it behind a Provider interface to allow
 *   swapping implementations if Sandbox verification reveals incompatibilities.
 *
 * Available implementations:
 * - XmlCryptoCanonicalizationProvider (primary, based on xml-crypto@6.1.2)
 * - XadesJsCanonicalizationProvider (future, fallback if xml-crypto incompatible)
 * - CustomCanonicalizationProvider (last resort, full control)
 *
 * Architectural Assumption (AA-002):
 *   "For the current invoice structures generated by this ERP, the output
 *    produced by the selected canonicalization implementation is assumed to be
 *    accepted by ZATCA Sandbox. This assumption remains pending until verified
 *    by Sandbox integration tests."
 *
 *   This is documented per AD-000 Part VIII: Architectural Assumption (AA-xxx),
 *   not a Decision. It will become a Fact only after Sandbox verifies it.
 *
 *   The Provider interface ensures that, should AA-002 be falsified by Sandbox,
 *   we can swap implementations without rebuilding S3.
 */

/**
 * Canonical XML representation.
 * Per AD-006 v2: the output of canonicalization is a byte stream (UTF-8).
 * For type-safety, we model it as a branded string.
 */
export type CanonicalXml = string & { readonly __brand: 'CanonicalXml' };

/**
 * Canonicalization algorithm identifier (W3C URI).
 *
 * ZATCA's spec declares: http://www.w3.org/2006/12/xml-c14n11 (C14N 1.1)
 * 
 * Per AA-002, we implement C14N 1.0 algorithmically. The XML declaration of
 * c14n11 is a separate concern handled by XmlBuilder, not the canonicalizer.
 */
export type CanonicalizationAlgorithm =
  | 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315'      // C14N 1.0
  | 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments' // C14N 1.0 with comments
  | 'http://www.w3.org/2001/10/xml-exc-c14n#'              // Exclusive C14N
  | 'http://www.w3.org/2006/12/xml-c14n11';                // C14N 1.1 (claimed only, see AA-002)

/**
 * Errors raised by CanonicalizationProvider.
 * Per AD-011 v2: errors are typed and carry actionable context.
 */
export class CanonicalizationError extends Error {
  constructor(
    public readonly code: CanonicalizationErrorCode,
    message: string,
    public readonly context?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'CanonicalizationError';
  }
}

export type CanonicalizationErrorCode =
  | 'INVALID_XML'           // Input XML cannot be parsed
  | 'UNSUPPORTED_ALGORITHM' // Algorithm URI not supported by this provider
  | 'CANONICALIZATION_FAILED' // Algorithm execution failed
  | 'EMPTY_INPUT';          // Input was empty or whitespace-only

/**
 * The CanonicalizationProvider interface.
 *
 * All implementations MUST:
 * 1. Accept well-formed XML as input.
 * 2. Apply CRLF → LF normalization (per AD-006 v2 and XML 1.0 spec).
 * 3. Strip UTF-8 BOM if present (per AD-006 v2).
 * 4. Return a deterministic byte-identical output for identical input.
 * 5. Document which W3C algorithm they implement.
 * 6. Throw CanonicalizationError on failure (no silent corruption).
 *
 * Determinism:
 *   For identical input, output MUST be byte-identical. This is verified by
 *   Golden Fixtures (per AD-006A v2).
 *
 * Thread-safety:
 *   Providers SHOULD be stateless and safe under concurrent calls.
 */
export interface CanonicalizationProvider {
  /**
   * The W3C algorithm URI this provider implements.
   * Used for logging, diagnostics, and consumer awareness.
   */
  readonly algorithm: CanonicalizationAlgorithm;

  /**
   * Human-readable name of the provider implementation.
   * E.g., "xml-crypto v6.1.2 C14N 1.0".
   */
  readonly implementationName: string;

  /**
   * Canonicalize an XML string.
   *
   * @param xml - Well-formed XML input as UTF-8 string
   * @returns Canonical XML as a UTF-8 string
   *
   * @throws CanonicalizationError on parse failure or algorithm error
   *
   * Important:
   * - Input may contain CRLF; output MUST contain LF only.
   * - Input may have UTF-8 BOM; output MUST NOT.
   * - Output is deterministic for identical input.
   */
  canonicalize(xml: string): CanonicalXml;
}

/**
 * Factory function signature for dependency injection.
 * Per AD-012 v2: providers injected through factories for determinism in tests.
 */
export type CanonicalizationProviderFactory = () => CanonicalizationProvider;
