/**
 * XmlCryptoCanonicalizationProvider — C14N 1.0 implementation via xml-crypto@6.1.2.
 *
 * Architectural references:
 * - AD-001 Pipeline Phase 2: Canonicalize XML
 * - AD-006 v2: Canonicalization Strategy
 * - AD-009A v2: One Authority Per Concern (canonicalization owned by this module)
 *
 * Why xml-crypto:
 * - Mature (463+ dependents, MIT, actively maintained)
 * - Production-grade XMLDSig infrastructure
 * - C14N 1.0 implementation is well-tested
 * - Aligns with reference implementations accepted by ZATCA (Saleh7 PHP, jibrid Node)
 *
 * What this provider does:
 *   1. Strip UTF-8 BOM if present
 *   2. Normalize CRLF → LF
 *   3. Parse XML using @xmldom/xmldom (strict, throws on malformed)
 *   4. Apply xml-crypto's C14nCanonicalization (W3C C14N 1.0)
 *   5. Return canonical XML as string
 *
 * What this provider does NOT do:
 * - Modify the XML declaration's c14n URI (that's XmlBuilder's concern, per AD-006 v2)
 * - Perform signing (that's XadesSigner, per AD-001 Phase 4)
 * - Validate UBL schema (that's a separate validator)
 *
 * Architectural Assumption AA-002:
 *   This implementation's output is assumed to be accepted by ZATCA Sandbox
 *   for the invoice structures generated by this ERP. Verification pending Sandbox.
 */

import { C14nCanonicalization } from 'xml-crypto';
import { DOMParser } from '@xmldom/xmldom';
import type {
  CanonicalizationProvider,
  CanonicalXml,
  CanonicalizationAlgorithm,
} from './CanonicalizationProvider';
import { CanonicalizationError } from './CanonicalizationProvider';

/**
 * UTF-8 BOM byte sequence as Unicode codepoint.
 * Per RFC 3629: BOM is U+FEFF.
 */
const UTF8_BOM = '\uFEFF';

export class XmlCryptoCanonicalizationProvider implements CanonicalizationProvider {
  readonly algorithm: CanonicalizationAlgorithm =
    'http://www.w3.org/TR/2001/REC-xml-c14n-20010315';

  readonly implementationName = 'xml-crypto@6.1.2 C14N 1.0';

  /**
   * Canonicalize XML using C14N 1.0 algorithm.
   *
   * Steps:
   * 1. Reject empty/whitespace-only input
   * 2. Strip UTF-8 BOM
   * 3. Normalize line endings (CRLF → LF)
   * 4. Parse with strict DOM parser
   * 5. Apply C14N 1.0 transformation
   */
  canonicalize(xml: string): CanonicalXml {
    // Step 1: Reject empty input
    if (!xml || xml.trim().length === 0) {
      throw new CanonicalizationError(
        'EMPTY_INPUT',
        'XML input is empty or whitespace-only'
      );
    }

    // Step 2: Strip UTF-8 BOM if present
    let normalized = xml.startsWith(UTF8_BOM) ? xml.slice(1) : xml;

    // Step 3: Normalize line endings (CRLF → LF, then any remaining CR → LF)
    // Per XML 1.0 §2.11 End-of-Line Handling
    normalized = normalized.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    // Step 4: Parse XML using strict parser
    let document;
    try {
      const parser = new DOMParser({
        // Throw on parse errors instead of silently degrading
        errorHandler: {
          warning: () => { /* suppress warnings */ },
          error: (msg: string) => {
            throw new CanonicalizationError(
              'INVALID_XML',
              `XML parse error: ${msg}`,
              { error: msg }
            );
          },
          fatalError: (msg: string) => {
            throw new CanonicalizationError(
              'INVALID_XML',
              `XML fatal parse error: ${msg}`,
              { error: msg }
            );
          },
        },
      });
      document = parser.parseFromString(normalized, 'text/xml');
    } catch (err) {
      if (err instanceof CanonicalizationError) throw err;
      throw new CanonicalizationError(
        'INVALID_XML',
        'XML could not be parsed',
        { cause: String(err) }
      );
    }

    // Defensive: ensure we have a document element
    if (!document?.documentElement) {
      throw new CanonicalizationError(
        'INVALID_XML',
        'XML parsed but has no document element'
      );
    }

    // Step 5: Apply C14N 1.0
    try {
      const canonicalizer = new C14nCanonicalization();
      const result = canonicalizer.process(document.documentElement, {
        ancestorNamespaces: [],
      });

      if (typeof result !== 'string') {
        throw new CanonicalizationError(
          'CANONICALIZATION_FAILED',
          'Canonicalizer returned non-string result',
          { resultType: typeof result }
        );
      }

      return result as CanonicalXml;
    } catch (err) {
      if (err instanceof CanonicalizationError) throw err;
      throw new CanonicalizationError(
        'CANONICALIZATION_FAILED',
        'Canonicalization algorithm failed',
        { cause: String(err) }
      );
    }
  }
}
